import Vue from 'vue'
import Router from 'vue-router'
import { normalizeURL, decode } from 'ufo'
import { interopDefault } from './utils'
import scrollBehavior from './router.scrollBehavior.js'

const _655f14c2 = () => interopDefault(import('../pages/about/index.vue' /* webpackChunkName: "pages/about/index" */))
const _6a6c4734 = () => interopDefault(import('../pages/blank-page.vue' /* webpackChunkName: "pages/blank-page" */))
const _6fa5eaa3 = () => interopDefault(import('../pages/blog/index.vue' /* webpackChunkName: "pages/blog/index" */))
const _1412fa1f = () => interopDefault(import('../pages/collection/index.vue' /* webpackChunkName: "pages/collection/index" */))
const _50278b15 = () => interopDefault(import('../pages/contact/index.vue' /* webpackChunkName: "pages/contact/index" */))
const _06347778 = () => interopDefault(import('../pages/index.vue' /* webpackChunkName: "pages/index" */))
const _72e5314a = () => interopDefault(import('../pages/login.vue' /* webpackChunkName: "pages/login" */))
const _0e22531b = () => interopDefault(import('../pages/marketing/index.vue' /* webpackChunkName: "pages/marketing/index" */))
const _7f9fafa1 = () => interopDefault(import('../pages/register.vue' /* webpackChunkName: "pages/register" */))
const _4540401d = () => interopDefault(import('../pages/soporte/index.vue' /* webpackChunkName: "pages/soporte/index" */))
const _81c271fc = () => interopDefault(import('../pages/webdev/index.vue' /* webpackChunkName: "pages/webdev/index" */))
const _3e34e11d = () => interopDefault(import('../pages/about/team.vue' /* webpackChunkName: "pages/about/team" */))
const _409b70af = () => interopDefault(import('../pages/blog/detail-blog.vue' /* webpackChunkName: "pages/blog/detail-blog" */))
const _4204ac76 = () => interopDefault(import('../pages/collection/detail-product.vue' /* webpackChunkName: "pages/collection/detail-product" */))
const _391c4227 = () => interopDefault(import('../pages/collection/products.vue' /* webpackChunkName: "pages/collection/products" */))
const _c059e93c = () => interopDefault(import('../pages/contact/with-map.vue' /* webpackChunkName: "pages/contact/with-map" */))
const _71ef942c = () => interopDefault(import('../pages/marketing/body/index.vue' /* webpackChunkName: "pages/marketing/body/index" */))
const _d6310f2c = () => interopDefault(import('../pages/soporte/body/index.vue' /* webpackChunkName: "pages/soporte/body/index" */))
const _f0dd0d4a = () => interopDefault(import('../pages/utils/coming-soon.vue' /* webpackChunkName: "pages/utils/coming-soon" */))
const _54a017ac = () => interopDefault(import('../pages/utils/faq.vue' /* webpackChunkName: "pages/utils/faq" */))
const _82384cb2 = () => interopDefault(import('../pages/utils/maintenance.vue' /* webpackChunkName: "pages/utils/maintenance" */))
const _04c012da = () => interopDefault(import('../pages/utils/pricing.vue' /* webpackChunkName: "pages/utils/pricing" */))
const _741b0eb6 = () => interopDefault(import('../pages/webdev/body/index.vue' /* webpackChunkName: "pages/webdev/body/index" */))

const emptyFn = () => {}

Vue.use(Router)

export const routerOptions = {
  mode: 'history',
  base: '/',
  linkActiveClass: 'nuxt-link-active',
  linkExactActiveClass: 'nuxt-link-exact-active',
  scrollBehavior,

  routes: [{
    path: "/about",
    component: _655f14c2,
    name: "about"
  }, {
    path: "/blank-page",
    component: _6a6c4734,
    name: "blank-page"
  }, {
    path: "/blog",
    component: _6fa5eaa3,
    name: "blog"
  }, {
    path: "/collection",
    component: _1412fa1f,
    name: "collection"
  }, {
    path: "/contact",
    component: _50278b15,
    name: "contact"
  }, {
    path: "/de",
    component: _06347778,
    name: "index___de"
  }, {
    path: "/en",
    component: _06347778,
    name: "index___en"
  }, {
    path: "/es",
    component: _06347778,
    name: "index___es"
  }, {
    path: "/login",
    component: _72e5314a,
    name: "login"
  }, {
    path: "/marketing",
    component: _0e22531b,
    name: "marketing"
  }, {
    path: "/pt",
    component: _06347778,
    name: "index___pt"
  }, {
    path: "/register",
    component: _7f9fafa1,
    name: "register"
  }, {
    path: "/soporte",
    component: _4540401d,
    name: "soporte"
  }, {
    path: "/webdev",
    component: _81c271fc,
    name: "webdev"
  }, {
    path: "/zh",
    component: _06347778,
    name: "index___zh"
  }, {
    path: "/about/team",
    component: _3e34e11d,
    name: "about-team"
  }, {
    path: "/blog/detail-blog",
    component: _409b70af,
    name: "blog-detail-blog"
  }, {
    path: "/collection/detail-product",
    component: _4204ac76,
    name: "collection-detail-product"
  }, {
    path: "/collection/products",
    component: _391c4227,
    name: "collection-products"
  }, {
    path: "/contact/with-map",
    component: _c059e93c,
    name: "contact-with-map"
  }, {
    path: "/de/about",
    component: _655f14c2,
    name: "about___de"
  }, {
    path: "/de/blank-page",
    component: _6a6c4734,
    name: "blank-page___de"
  }, {
    path: "/de/blog",
    component: _6fa5eaa3,
    name: "blog___de"
  }, {
    path: "/de/collection",
    component: _1412fa1f,
    name: "collection___de"
  }, {
    path: "/de/contact",
    component: _50278b15,
    name: "contact___de"
  }, {
    path: "/de/login",
    component: _72e5314a,
    name: "login___de"
  }, {
    path: "/de/marketing",
    component: _0e22531b,
    name: "marketing___de"
  }, {
    path: "/de/register",
    component: _7f9fafa1,
    name: "register___de"
  }, {
    path: "/de/soporte",
    component: _4540401d,
    name: "soporte___de"
  }, {
    path: "/de/webdev",
    component: _81c271fc,
    name: "webdev___de"
  }, {
    path: "/en/about",
    component: _655f14c2,
    name: "about___en"
  }, {
    path: "/en/blank-page",
    component: _6a6c4734,
    name: "blank-page___en"
  }, {
    path: "/en/blog",
    component: _6fa5eaa3,
    name: "blog___en"
  }, {
    path: "/en/collection",
    component: _1412fa1f,
    name: "collection___en"
  }, {
    path: "/en/contact",
    component: _50278b15,
    name: "contact___en"
  }, {
    path: "/en/login",
    component: _72e5314a,
    name: "login___en"
  }, {
    path: "/en/marketing",
    component: _0e22531b,
    name: "marketing___en"
  }, {
    path: "/en/register",
    component: _7f9fafa1,
    name: "register___en"
  }, {
    path: "/en/soporte",
    component: _4540401d,
    name: "soporte___en"
  }, {
    path: "/en/webdev",
    component: _81c271fc,
    name: "webdev___en"
  }, {
    path: "/es/about",
    component: _655f14c2,
    name: "about___es"
  }, {
    path: "/es/blank-page",
    component: _6a6c4734,
    name: "blank-page___es"
  }, {
    path: "/es/blog",
    component: _6fa5eaa3,
    name: "blog___es"
  }, {
    path: "/es/collection",
    component: _1412fa1f,
    name: "collection___es"
  }, {
    path: "/es/contact",
    component: _50278b15,
    name: "contact___es"
  }, {
    path: "/es/login",
    component: _72e5314a,
    name: "login___es"
  }, {
    path: "/es/marketing",
    component: _0e22531b,
    name: "marketing___es"
  }, {
    path: "/es/register",
    component: _7f9fafa1,
    name: "register___es"
  }, {
    path: "/es/soporte",
    component: _4540401d,
    name: "soporte___es"
  }, {
    path: "/es/webdev",
    component: _81c271fc,
    name: "webdev___es"
  }, {
    path: "/marketing/body",
    component: _71ef942c,
    name: "marketing-body"
  }, {
    path: "/pt/about",
    component: _655f14c2,
    name: "about___pt"
  }, {
    path: "/pt/blank-page",
    component: _6a6c4734,
    name: "blank-page___pt"
  }, {
    path: "/pt/blog",
    component: _6fa5eaa3,
    name: "blog___pt"
  }, {
    path: "/pt/collection",
    component: _1412fa1f,
    name: "collection___pt"
  }, {
    path: "/pt/contact",
    component: _50278b15,
    name: "contact___pt"
  }, {
    path: "/pt/login",
    component: _72e5314a,
    name: "login___pt"
  }, {
    path: "/pt/marketing",
    component: _0e22531b,
    name: "marketing___pt"
  }, {
    path: "/pt/register",
    component: _7f9fafa1,
    name: "register___pt"
  }, {
    path: "/pt/soporte",
    component: _4540401d,
    name: "soporte___pt"
  }, {
    path: "/pt/webdev",
    component: _81c271fc,
    name: "webdev___pt"
  }, {
    path: "/soporte/body",
    component: _d6310f2c,
    name: "soporte-body"
  }, {
    path: "/utils/coming-soon",
    component: _f0dd0d4a,
    name: "utils-coming-soon"
  }, {
    path: "/utils/faq",
    component: _54a017ac,
    name: "utils-faq"
  }, {
    path: "/utils/maintenance",
    component: _82384cb2,
    name: "utils-maintenance"
  }, {
    path: "/utils/pricing",
    component: _04c012da,
    name: "utils-pricing"
  }, {
    path: "/webdev/body",
    component: _741b0eb6,
    name: "webdev-body"
  }, {
    path: "/zh/about",
    component: _655f14c2,
    name: "about___zh"
  }, {
    path: "/zh/blank-page",
    component: _6a6c4734,
    name: "blank-page___zh"
  }, {
    path: "/zh/blog",
    component: _6fa5eaa3,
    name: "blog___zh"
  }, {
    path: "/zh/collection",
    component: _1412fa1f,
    name: "collection___zh"
  }, {
    path: "/zh/contact",
    component: _50278b15,
    name: "contact___zh"
  }, {
    path: "/zh/login",
    component: _72e5314a,
    name: "login___zh"
  }, {
    path: "/zh/marketing",
    component: _0e22531b,
    name: "marketing___zh"
  }, {
    path: "/zh/register",
    component: _7f9fafa1,
    name: "register___zh"
  }, {
    path: "/zh/soporte",
    component: _4540401d,
    name: "soporte___zh"
  }, {
    path: "/zh/webdev",
    component: _81c271fc,
    name: "webdev___zh"
  }, {
    path: "/de/about/team",
    component: _3e34e11d,
    name: "about-team___de"
  }, {
    path: "/de/blog/detail-blog",
    component: _409b70af,
    name: "blog-detail-blog___de"
  }, {
    path: "/de/collection/detail-product",
    component: _4204ac76,
    name: "collection-detail-product___de"
  }, {
    path: "/de/collection/products",
    component: _391c4227,
    name: "collection-products___de"
  }, {
    path: "/de/contact/with-map",
    component: _c059e93c,
    name: "contact-with-map___de"
  }, {
    path: "/de/marketing/body",
    component: _71ef942c,
    name: "marketing-body___de"
  }, {
    path: "/de/soporte/body",
    component: _d6310f2c,
    name: "soporte-body___de"
  }, {
    path: "/de/utils/coming-soon",
    component: _f0dd0d4a,
    name: "utils-coming-soon___de"
  }, {
    path: "/de/utils/faq",
    component: _54a017ac,
    name: "utils-faq___de"
  }, {
    path: "/de/utils/maintenance",
    component: _82384cb2,
    name: "utils-maintenance___de"
  }, {
    path: "/de/utils/pricing",
    component: _04c012da,
    name: "utils-pricing___de"
  }, {
    path: "/de/webdev/body",
    component: _741b0eb6,
    name: "webdev-body___de"
  }, {
    path: "/en/about/team",
    component: _3e34e11d,
    name: "about-team___en"
  }, {
    path: "/en/blog/detail-blog",
    component: _409b70af,
    name: "blog-detail-blog___en"
  }, {
    path: "/en/collection/detail-product",
    component: _4204ac76,
    name: "collection-detail-product___en"
  }, {
    path: "/en/collection/products",
    component: _391c4227,
    name: "collection-products___en"
  }, {
    path: "/en/contact/with-map",
    component: _c059e93c,
    name: "contact-with-map___en"
  }, {
    path: "/en/marketing/body",
    component: _71ef942c,
    name: "marketing-body___en"
  }, {
    path: "/en/soporte/body",
    component: _d6310f2c,
    name: "soporte-body___en"
  }, {
    path: "/en/utils/coming-soon",
    component: _f0dd0d4a,
    name: "utils-coming-soon___en"
  }, {
    path: "/en/utils/faq",
    component: _54a017ac,
    name: "utils-faq___en"
  }, {
    path: "/en/utils/maintenance",
    component: _82384cb2,
    name: "utils-maintenance___en"
  }, {
    path: "/en/utils/pricing",
    component: _04c012da,
    name: "utils-pricing___en"
  }, {
    path: "/en/webdev/body",
    component: _741b0eb6,
    name: "webdev-body___en"
  }, {
    path: "/es/about/team",
    component: _3e34e11d,
    name: "about-team___es"
  }, {
    path: "/es/blog/detail-blog",
    component: _409b70af,
    name: "blog-detail-blog___es"
  }, {
    path: "/es/collection/detail-product",
    component: _4204ac76,
    name: "collection-detail-product___es"
  }, {
    path: "/es/collection/products",
    component: _391c4227,
    name: "collection-products___es"
  }, {
    path: "/es/contact/with-map",
    component: _c059e93c,
    name: "contact-with-map___es"
  }, {
    path: "/es/marketing/body",
    component: _71ef942c,
    name: "marketing-body___es"
  }, {
    path: "/es/soporte/body",
    component: _d6310f2c,
    name: "soporte-body___es"
  }, {
    path: "/es/utils/coming-soon",
    component: _f0dd0d4a,
    name: "utils-coming-soon___es"
  }, {
    path: "/es/utils/faq",
    component: _54a017ac,
    name: "utils-faq___es"
  }, {
    path: "/es/utils/maintenance",
    component: _82384cb2,
    name: "utils-maintenance___es"
  }, {
    path: "/es/utils/pricing",
    component: _04c012da,
    name: "utils-pricing___es"
  }, {
    path: "/es/webdev/body",
    component: _741b0eb6,
    name: "webdev-body___es"
  }, {
    path: "/pt/about/team",
    component: _3e34e11d,
    name: "about-team___pt"
  }, {
    path: "/pt/blog/detail-blog",
    component: _409b70af,
    name: "blog-detail-blog___pt"
  }, {
    path: "/pt/collection/detail-product",
    component: _4204ac76,
    name: "collection-detail-product___pt"
  }, {
    path: "/pt/collection/products",
    component: _391c4227,
    name: "collection-products___pt"
  }, {
    path: "/pt/contact/with-map",
    component: _c059e93c,
    name: "contact-with-map___pt"
  }, {
    path: "/pt/marketing/body",
    component: _71ef942c,
    name: "marketing-body___pt"
  }, {
    path: "/pt/soporte/body",
    component: _d6310f2c,
    name: "soporte-body___pt"
  }, {
    path: "/pt/utils/coming-soon",
    component: _f0dd0d4a,
    name: "utils-coming-soon___pt"
  }, {
    path: "/pt/utils/faq",
    component: _54a017ac,
    name: "utils-faq___pt"
  }, {
    path: "/pt/utils/maintenance",
    component: _82384cb2,
    name: "utils-maintenance___pt"
  }, {
    path: "/pt/utils/pricing",
    component: _04c012da,
    name: "utils-pricing___pt"
  }, {
    path: "/pt/webdev/body",
    component: _741b0eb6,
    name: "webdev-body___pt"
  }, {
    path: "/zh/about/team",
    component: _3e34e11d,
    name: "about-team___zh"
  }, {
    path: "/zh/blog/detail-blog",
    component: _409b70af,
    name: "blog-detail-blog___zh"
  }, {
    path: "/zh/collection/detail-product",
    component: _4204ac76,
    name: "collection-detail-product___zh"
  }, {
    path: "/zh/collection/products",
    component: _391c4227,
    name: "collection-products___zh"
  }, {
    path: "/zh/contact/with-map",
    component: _c059e93c,
    name: "contact-with-map___zh"
  }, {
    path: "/zh/marketing/body",
    component: _71ef942c,
    name: "marketing-body___zh"
  }, {
    path: "/zh/soporte/body",
    component: _d6310f2c,
    name: "soporte-body___zh"
  }, {
    path: "/zh/utils/coming-soon",
    component: _f0dd0d4a,
    name: "utils-coming-soon___zh"
  }, {
    path: "/zh/utils/faq",
    component: _54a017ac,
    name: "utils-faq___zh"
  }, {
    path: "/zh/utils/maintenance",
    component: _82384cb2,
    name: "utils-maintenance___zh"
  }, {
    path: "/zh/utils/pricing",
    component: _04c012da,
    name: "utils-pricing___zh"
  }, {
    path: "/zh/webdev/body",
    component: _741b0eb6,
    name: "webdev-body___zh"
  }, {
    path: "/",
    component: _06347778,
    name: "index"
  }],

  fallback: false
}

export function createRouter (ssrContext, config) {
  const base = (config._app && config._app.basePath) || routerOptions.base
  const router = new Router({ ...routerOptions, base  })

  // TODO: remove in Nuxt 3
  const originalPush = router.push
  router.push = function push (location, onComplete = emptyFn, onAbort) {
    return originalPush.call(this, location, onComplete, onAbort)
  }

  const resolve = router.resolve.bind(router)
  router.resolve = (to, current, append) => {
    if (typeof to === 'string') {
      to = normalizeURL(to)
    }
    return resolve(to, current, append)
  }

  return router
}
